### ISSUE TITLE
Not able to render

### ISSUE THREAD

**Issue by arpit-g** [rohitgirdhar/Deep-Q-Networks#3]
Hi,

Thanks for providing the code. I am facing an issue when I try to render the environment. I have made --render flag as true but it gives import error: library C not found when importing pyglet.

I have added the line env.render() inside "if render:" condition. Also, what is render_path? Following is the traceback

Traceback (most recent call last):
  File "/home/arpit/.local/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 221, in <module>
    from .xlib import XlibConfig as Config
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 12, in <module>
    from pyglet.canvas.xlib import XlibCanvas
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 103, in <module>
    from pyglet.canvas.xlib import XlibDisplay as Display
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 16, in <module>
    from pyglet.app.xlib import XlibSelectDevice
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/app/__init__.py", line 175, in <module>
    event_loop = EventLoop()
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/app/base.py", line 119, in __init__
    self.clock = clock.get_default()
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/clock.py", line 169, in <module>
    _c = pyglet.lib.load_library('c')
  File "/home/arpit/.local/lib/python3.6/site-packages/pyglet/lib.py", line 158, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "c" not found.

Waiting for your response.

**Comment by arpit-g** [comment]
Solved it using other method.
